# Generated by Django 5.2 on 2025-04-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="labels",
        ),
    ]
