# Generated by Django 5.2 on 2025-04-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_labeltask_task_labels"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assigned_to",
            new_name="executor",
        ),
    ]
