# Generated by Django 5.2 on 2025-04-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='author',
        ),
    ]
